config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'homes/about'
  devise_for :users
  resources :users, only: [:index, :show, :edit, :create, :update, :destroy]
  resources :books, only: [:index, :show, :edit, :create, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_one_attached :profile_image

  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  before_action :authenticate_user!, except: [:top, :about]



  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
     root_path
  end



  protected

  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
  end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @book.save
    redirect_to book_path(@book.id)
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @newbook = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    redirect_to book_path(@book.id)
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def is_matching_login_user
    book = Book.find(params[:id])
    unless book.user.id == current_user.id
      redirect_to books_path
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def index
    @book = Book.new
    @users = User.all
  end

  def show
   @user = User.find(params[:id])
   @book = Book.new
   @books = @user.books.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to books_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-4">
      <h1>Editing Book</h1>
      <%= form_with model: @book, method: :patch do |f| %>
        <p>Title</p>
        <%= f.text_field :title, class: "form-control mb-4" %>
        <p>Opinion</p>
        <%= f.text_area :body, class: "form-control" %>
        <%= f.submit "Update Book", class: "btn btn-success my-4" %>
      <% end %>
      <%= link_to "Show", book_path(@book.id) %> | <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <div class="mr-5 col-4 justify-content-center">
      <h1>User info</h1>
      <%= image_tag current_user.get_profile_image(100, 100) %>
      <table class="table">
        <tbody>
          <tr>
            <th scope="col">name</th>
            <th scope="col"><%= current_user.name %></th>
          </tr>
          <tr>
            <th scope="row">introduction</th>
            <td><%= current_user.introduction %></td>
        </tbody>
      </table>
      <%= link_to edit_user_path(current_user.id), class: "btn btn-outline-secondary col-12" do %>
        <i class="fa-solid fa-user-gear"></i>
      <% end %>
    </div>
    <div class="ml-4 col-7 justify-content-center">
      <h1>Books</h1>
      <table class="table">
        <tbody>
          <tr>
            <th></th>
            <td>Title</td>
            <td>Opinion</td>
          </tr>
          <% @books.each do |book| %>
          <tr>
            <td><%= image_tag book.user.get_profile_image(100, 100) %></td>
            <td>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </td>
            <td><%= book.body %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-4 justify-content-center mt-5">
      <h1>New book</h1>
      <%= form_with model: @book do |f| %>
        <p>Title</p>
        <%= f.text_field :title %>
        <p>Opinion</p>
        <%= f.text_area :body %><br>
        <%= f.submit "Create Book", class: "btn btn-success col-4 mt-3" %>
      <% end %>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="mr-5 col-4 justify-content-center">
      <h1>User info</h1>
      <%= image_tag current_user.get_profile_image(100, 100) %>
      <table class="table">
        <tbody>
          <tr>
            <th scope="col">name</th>
            <th scope="col"><%= current_user.name %></th>
          </tr>
          <tr>
            <th scope="row">introduction</th>
            <td><%= current_user.introduction %></td>
        </tbody>
      </table>
      <%= link_to edit_user_path(current_user.id), class: "btn btn-outline-secondary col-12" do %>
        <i class="fa-solid fa-user-gear"></i>
      <% end %>
    </div>
    <div class="ml-4 col-7 justify-content-center">
      <h1>Book detail</h1>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= image_tag @book.user.get_profile_image(100, 100) %><br>
              <%= link_to user_path(@book.id) do %>
                <%= @book.user.name %>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(@book.id) do %>
                <%= @book.title %>
              <% end %>
            </td>
            <td><%= @book.body %></td>
            <% if @book.user.id == current_user.id %>
              <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-success" %></td>
              <td><%= button_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に削除しますか?", class: "btn btn-danger" %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-4 justify-content-center mt-5">
      <h1>New book</h1>
      <%= form_with model: @newbook do |f| %>
        <p>Title</p>
        <%= f.text_field :title %>
        <p>Opinion</p>
        <%= f.text_area :body %><br>
        <%= f.submit "Create Book", class: "btn btn-success col-4 mt-3" %>
      <% end %>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <h1>Welcome to <i class="fa-solid fa-book"></i><b>Bookers</b>!</h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
      <h1>Welcome to <i class="fa-solid fa-book"></i><b>Bookers</b> !!
        <h6>In <i class="fa-solid fa-book"></i><b>Bookers</b>,</h6>
      </h1>
    </div>
  </div>
  <div class="row justify-content-center mt-3">
    <div class="col-6">
      <p>you can share and exchange your opinions, inpressions, and emotions</p>
      <p>about various books!</p>
    </div>
  </div>
  <div class="row justify-content-center mb-3">
    <div class="col-6">
      <%= link_to "Log in", new_user_session_path, class: "btn btn-primary col-10" %>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-6">
      <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success col-10" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <script src="https://kit.fontawesome.com/ec197d3cc7.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="mb-5">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
         <a class="navbar-brand" href="/"><span>Bookers</span></a>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
         </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li>
                  <%= link_to user_path(current_user.id),class: "nav-link text-white" do %>
                  <i class="fas fa-home"></i>Home
                  <% end %>
                </li>
                <li>
                  <%= link_to users_path,class: "nav-link text-white"  do %>
                  <i class="fas fa-users"></i>Users
                  <% end %>
                </li>
                <li>
                  <%= link_to books_path,class: "nav-link text-white" do %>
                  <i class="fas fa-book-open"></i>Books
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete,class: "nav-link text-white" do %>
                  <i class="fas fa-sign-out-alt"></i>Log out
                  <% end %>
                </li>
              <% else %>
                <li>
                  <%= link_to root_path,class: "nav-link text-light" do %>
                    <i class="fas fa-home"></i>Home
                  <% end %>
                </li>
                <li>
                  <%= link_to homes_about_path,class: "nav-link text-light" do %>
                    <i class="fas fa-link"></i>About
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_registration_path,class: "nav-link text-light" do %>
                    <i class="fas fa-user-plus"></i>Sign up
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_session_path,class: "nav-link text-light" do %>
                    <i class="fas fa-sign-in-alt"></i>Log in
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>

    </header>
    <main>
      <%= yield %>
    </main>
    <footer class="text-center mt-5">
      <h6>CopyRight Infratop.inc</h6>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-4">
      <h1>User info</h1>
      <%= form_with model: @user, method: :patch do |f| %>
      <p>Name</p>
      <%= f.text_field :name, class: "form-control" %>
      <p class="mt-3">Image</p>
      <%= f.file_field :profile_image, accept: "image/*" %>
      <p class="mt-3">Introduction</p>
      <%= f.text_area :introduction, class: "form-control" %><br>
      <%= f.submit "Update User", class: "btn btn-secondary mt-3" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="mr-5 col-4 justify-content-center">
      <h1>User info</h1>
      <%= image_tag current_user.get_profile_image(100, 100) %>
      <table class="table">
        <tbody>
          <tr>
            <th scope="col">name</th>
            <th scope="col"><%= current_user.name %></th>
          </tr>
          <tr>
            <th scope="row">introduction</th>
            <td><%= current_user.introduction %></td>
        </tbody>
      </table>
      <%= link_to edit_user_path(current_user.id), class: "btn btn-outline-secondary col-12" do %>
        <i class="fa-solid fa-user-gear"></i>
      <% end %>
    </div>
    <div class="ml-4 col-7 justify-content-center">
      <h1>Users</h1>
      <table class="table">
        <tbody>
          <tr>
            <th scope="col">image</th>
            <th scope="col">name</th>
            <td colspan="3" class="ml-5"></td>
          </tr>
          <% @users.each do |user| %>
          <tr>
            <td scope="col"><%= image_tag user.get_profile_image(100, 100) %></td>
            <td scope="col">
              <%= user.name %>
            </td>
            <td scope="col" class="ml-5"><%= link_to "Show", user_path(user.id) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-4 justify-content-center mt-5">
      <h1>New book</h1>
      <%= form_with model: @book do |f| %>
        <p>Title</p>
        <%= f.text_field :title %>
        <p>Opinion</p>
        <%= f.text_area :body %><br>
        <%= f.submit "Create Book", class: "btn btn-success col-4 mt-3" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="mr-5 col-4 justify-content-center">
      <h1>User info</h1>
      <%= image_tag @user.get_profile_image(100, 100) %>
      <table class="table">
        <tbody>
          <tr>
            <th scope="col">name</th>
            <th scope="col"><%= @user.name %></th>
          </tr>
          <tr>
            <th scope="row">introduction</th>
            <td><%= @user.introduction %></td>
        </tbody>
      </table>
      <% if @user.id == current_user.id %>
        <%= link_to edit_user_path(@user.id), class: "btn btn-outline-secondary col-12" do %>
          <i class="fa-solid fa-user-gear"></i>
        <% end %>
      <% end %>
    </div>
    <div class="ml-4 col-7 justify-content-center">
      <h1>Books</h1>
      <table class="table">
        <tbody>
          <tr>
            <th scope="col"></th>
            <th scope="col">Title</th>
            <th scope="col">Opinion</th>
          </tr>
          <% @books.each do |book| %>
          <tr>
            <td><%= image_tag book.user.get_profile_image(100, 100) %></td>
            <td class="col-3">
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </td>
            <td class="col"><%= book.body %></td>
          </tr>
           <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-4 justify-content-center mt-5">
      <h1>New book</h1>
      <%= form_with model: @book do |f| %>
        <p>Title</p>
        <%= f.text_field :title %>
        <p>Opinion</p>
        <%= f.text_area :body %><br>
        <%= f.submit "Create Book", class: "btn btn-success col-4 mt-3" %>
      <% end %>
    </div>
  </div>
</div>